title: My WildCat Studios Portfolio description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: ""
url: "https://Sil1yseal.github.io"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
